<p><strong>References</strong></p>

<p>

Liti G, Carter DM, Moses AM, Warringer J, Parts L, James SA, Davey RP, Roberts IN, Burt A, Koufopanou V, Tsai IJ, Bergman CM, Bensasson D, O'Kelly MJ, van Oudenaarden A, Barton DB, Bailes E, Nguyen AN, Jones M, Quail MA, Goodhead I, Sims S, Smith F, Blomberg A, Durbin R, Louis EJ.
<br/>
<strong>Population genomics of domestic and wild yeasts. </strong> <br/>
<em> Nature. 2009 Mar 19;458(7236):337-41. Epub 2009 Feb 11. </em> <br/>
<a href="http://www.pubmedcentral.nih.gov/articlerender.fcgi?tool=pubmed&pubmedid=19212322" rel="external">PubMed 19212322</a>

</p>
