package EG::PomBase::SiteDefs;
use strict;
sub update_conf {
    $SiteDefs::ENSEMBL_LOGINS = 0;
    $SiteDefs::ENSEMBL_PORT           = 8024;
    $SiteDefs::ENSEMBL_SERVERNAME     = 'genomebrowser.pombase.org';

    $SiteDefs::ENSEMBL_PRIMARY_SPECIES  = 'Schizosaccharomyces_pombe';
    $SiteDefs::ENSEMBL_SECONDARY_SPECIES  = 'Schizosaccharomyces_pombe';
    $SiteDefs::__species_aliases{ 'Schizosaccharomyces_pombe' } = [qw(sp spac spbc spcc pombe schizosaccharomyces S_pombe)];
    
    $SiteDefs::__species_aliases{ 'Schizosaccharomyces_cryophilus' } = [qw(Schizosaccharomyces_cryophilus)];
    $SiteDefs::__species_aliases{ 'Schizosaccharomyces_japonicus' } = [qw(sj)];
    $SiteDefs::__species_aliases{ 'Schizosaccharomyces_octosporus' } = [qw(Schizosaccharomyces_octosporus)];
    
    $SiteDefs::SITE_NAME = 'PomBase';
    $SiteDefs::ENSEMBL_SITETYPE = 'PomBase';
    $SiteDefs::SITE_FTP= 'ftp://ftp.ensemblgenomes.org/pub/spombe';

    @SiteDefs::ENSEMBL_PERL_DIRS    = (
                                           $SiteDefs::ENSEMBL_SERVERROOT.'/perl',
                                           $SiteDefs::ENSEMBL_SERVERROOT.'/eg-web-common/perl',
                                           $SiteDefs::ENSEMBL_SERVERROOT.'/eg-web-pombase/perl'
                                       );
    $SiteDefs::ENA_COLLECTION_ID = 221;
    $SiteDefs::ENA_SAMPLE_SEQ = "TTATGTCGATGACATACTATTCAGAGAATGTTCTTTCCCGACTAGGAAGGGAAGTCGGAGTTATTCCGTTGGAGACCACAACCCCAGGCTCTCCCCACAGTCCACAAAAACCCCATTCGCAAAGCCATGGAGAGGTGGGCACAGACCGTCTGAACCACTCGGTCGAGGTTCACCAATCAATTTCATTCTCTCAATGTTCCTGGTCCCTACCGCGGGAATTTAGCCGGGCAGCCCGTCTAAATGACCCCAAACAACCGTCGGATTGCCGATGATGGGCTTATCATCGGCGTCGCGCGGCGATATATCCCGTCCGTTATCCCCAGTCTTCAGGTTGTCGCGGCCGACTGTGGGGTTTTTTACACTCCGTTCATCGTCACTCTTGCCAGAAACGTAACCTCATTCGTCTGGATCAGGTCTCCATTGCTCCCTCCCGGCTTTGATTCGGCTCGTCAGTGAGGTCGATGTGCAGTCCTCAGGCCAGCATAAGTAGTCCTGTAACCCCACACGTACCCTCACTTTTTTTCCCCCCTTGCGAGCGAGCTTTATTGTAGTGGCAGATTGAGCTTCTAATATCTTCATTGTTGATACCCAACGCCCATCATGAGTGATCAAATATCCTCGTGGAATGTCGTCCACAAGTTCGAAAAGCGCGGCCTTCTCATCGCCATTAACTGCGTGGCTGCCCTGTCAATCCTTTTCTTTGGATATGACCAGGGTATGATGTCTGGAGTGAACAACTCCAAGGACTATATCGATCTCATGGGGTTTGGCTATACGGAGATGAAGGATGGCCACCCTTCCCCCGTGGTGACCAACAGTCTGCTCCAAGGCGGCATCGTCAGTGTCTATTATTTAGGTACGCTCTTCGGTGCGCTGGTTGGCGGTTGGACTGGAGACAAGGTTGGTAGAATCAAGACGATTGCCTTCGGCTCAGTCTGGGCCATGTTTGGGGCCGCTCTACAGTGCTCAGCCCAGAACCACGACTGGATGATCTGCGGTTAGCCGTCTTGCCCGATCCCTGTGTTTTTGTGACTTTTCTAGCTGACTTAGGTAGCGCGATTTATAAACGGAATTGGAACCGGAATACTCAACGCGATTGTTCCCGTATGGGCGACCGAGACTGCAGAACACACGAGTCGTGGCCAGTTCATTGCAATCGAGTTCACACTGAACATCTTCGGTGTCGTGCTCGCATATTGGCTTGAATTGTAAGCAATAGAAGAAGCCAACTTGGACCATGCACTAACGATCATACAGCGGCCTGTCTTTCATCGATAACGGCGCATCGCCCTTCCGCTGGCGCTTCCCGATCGCGTTCCAAATCATCTTCTTGCTCGTTCTATTCGCCGCCGTTTGGTTCTTCCCGGAATCCCCACGTTGGTTGGTGAAGGTTGGTCGGGAGCAGGAGGCTCGGTATATTCTGGGTAGGCTGCGTGGCAGCAGCGGTGAAGATGCCATCCGGGCCGAGGCCGAGTTCCAGGATATTCTCAGCGTCGCGGAGGCAGAGAGGTCCATGGGCCACAGCACGTCTTACCTGGCTATGCTTTTCGGATACAAGACCGGGAAGTTGCATCTTGGCCGCCGGGTTCAACTTGTGGTATGGCTACAGATCATGCAGGAGTGGGTTGGTATTGCCGGTGTTGACTGTTTGTACGTCGCCCTTGAGATAATGTCGGGCCCAGGCTAATGGTTCTGCAGATGCCCCGACTATTTTCAGCATTGCAGGATTCGATTCCATGAAGAGTCAATGGATCAGCGGTTTAAACAACGTCTTTTACATGGTATGTCGTCCTTCTCTGGGCTTGGTACAGGCACATGCTAACAGAACAGTTTGCTACTATGATCTGTGTCTTTACTCTCGACCGAATCGGCCGTCGGTGGACTTTGTACTGGGGAGCTGCAGCCCAAGGAATCGCCATGTTCCTTGCTGGGGGTTTCTCACGTGTTTCGATCGACGCACGAGATGCGGGCAACATGGCGCGAGCTGAATCATTCGGTGCTGCTGCAGCGTCCATGGTTTTTGTATTCACCGCGGTCTTCGGAGCCACCTGGCTCACAGTGCCTTGGATCTATCCTGCGGAGATTTATCCATTAGCCGTCCGTGCAAAGGGTAATGCCTGGGGTGTTGTCGGCTGGAGTATTGGAAACGGATGGTTGGTGAGTGGTCGTGACCAAATTACAAATTTCTAAGCACGCACTAAACTATAGCTCTACAGACCCTCCTCTGCCCTGTGATGTTTGAAGCCATCGGGGAGAAGACCCTCTACGTATTCGCTGCCAGCAACGTGATCGCGATTCCAATGGTCTGGGCATTATACCCAGAGAGTAACCAGCGGACGCTAGAGGATATGGACCTGCTATTCGCTGCTGATACGCCTTGGGTGTGGGATGCAGAGAAGACATTTGCCCGCCTCAAGGCTGAGAACCCCGGGTTTATTGAGACCGCCGCGCGGAAGAATAGCGTGCTGGATGAGGAGGCTGCCAAGTCGGTGACTCTGGCGCATCGTGAAACTGTCGCTTGACAAGTTAAGATGAGATACCTTGTGATAGAGCAGGTGTAATTCAAGATAGCACCTCAAGAGAAATTATTATATAAAAGGCCATAATCGTAATTTGCCTTTGGTTTAGCCCTAGTATAACTAGTTTGATCATTGAGATTGAACTGCCTTCATTCTGCATAGTATGCAGACATAGGACATAGACAAAGCGAGAGTGCCAGAGAGTTCTGTACATGCGCTTACAGGAGGTAGAAGAGGCTTATGCGGGGAAATCCGAGCAATCCCCGCATCACGTTTTACCGGCCGGGCCAGATCGTGGCTAGTGCATTTGTACCAGCCACATACCCAAAACCTCGATACGTGGTGTATCCGGTCCCTAGTTAATCCGGGCCGTTTCCAGCTCCCAACACCAAAAGCACAGCTGGCATTAGTAGTATCACCACCCACGCTATCTCGACTTTCAACCTGCCACTCCTCCCTTTCGATCAATCCTTGTCTTTAGATCTCTCCACGTCCTGTCTACAGTGTTAATTTAGTCATAATTCGCCATCATGTCCGAACAAGTACAGGAATTGCTCAACATCCCTCAGGAGTTCCTTCGCGATGGAATGCAGTTTGTGAACCGCAGTCAGAAGCGTATGCATAGCCTTTTCTCTCTCATTTTATCTGTTTCAACTCCCTGGATCGTGTT";


}

1;
