<h2 class="first"><i>Aspergillus</i> genomes in Ensembl</h2> 
 
<h3>Database construction and maintenance</h3> 
<p class="space-below">
<img src="http://www.mhs.manchester.ac.uk/includes/tabs/v1_2/images/logomanchester.gif" align="LEFT" style="padding-right:10px;" /> 
Aspergillus genome sequences and annotation are maintained and curated in an Ensembl schema by the <a href="http://www.cadre-genomes.org.uk">Central Aspergillus Data Repository</a> and made available for inclusion within Ensembl Genomes.  
CADRE is operated at the School of Medicine at the University of Manchester. 
More information about the CADRE management team is provided <a href="http://www.cadre-genomes.org.uk/info/about/ManagementTeam.html">here</a>.
</p>
 <br/>
<ul> 
<li> 
<b>CADRE: the Central Aspergillus Data REpository.</b> 
<p>J. E. Mabey, M. J. Anderson, P. F. Giles, C. J. Miller, T. K. Attwood, N. W. Paton, E. Bornberg-Bauer, G. D. Robson, S. G. Oliver and D. W. Denning
</p> 
<p> <a href="http://nar.oxfordjournals.org/cgi/content/full/32/suppl_1/D401">Nucleic Acids Research, 2004, Vol. 32, Database issue D401-D405</a></p> 
</li> 
</ul> 
<br /> 
<p> 
We request that users of <i>Aspergillus</i> data from this site cite both CADRE and Ensembl Genomes. 
</p> 
 
<h3>Funding</h3> 
<a href="http://www.cadre-genomes.org.uk">C<i>A</i>DRE</a> is currently funded by 
<a href="http://www.sybaris-fp7.eu">SYBARIS</a>, an EU Framework Programe 7 collaborative project, grant agreement number 242220.
