<h2 class="first"> Featured content</h2>                                                                                                                                                                                                    
<p>
The ninth release of Ensembl Fungi includes three new plant pathogen species: <i>Fusarium oxysporum</i>, <i>Gibberella moniliformis</i>, and <i>Gibberella zeae</i>.
The gene set and the assembly for the yeast <i>Saccharomyces cerevisiae</i> have also been updated and are now in synchrony with <a href="http://www.yeastgenome.org">SGD</a>.
</p>
